update_settings(max_parallel_updates=1)

watch_file('/repo/k8s/endpoint/')
watch_file('/repo/k8s/extension_deployment/')
watch_file('/repo/k8s/extension_job/')
watch_file('/repo/k8s/extension_static/')

if config.tilt_subcommand == 'down':
  local('kubectl delete cm -l lxc.liferay.com/metadataType=ext-init')

def process_extension(
    name, projectPath, yamlTemplateName, virtual_instance_id='dxp.localdev.me', source_deps = [],
    objects = [], port_forwards = [], resource_deps = [], links = []):

  custom_build(
    name,
    "/workspace/gradlew :%s:buildClientExtensionDockerImage --stacktrace -PimageId=$EXPECTED_REF" % projectPath.replace("/", ":"),
    deps=[
      '/workspace/%s/src' % projectPath,
      '/workspace/%s/build.gradle' % projectPath,
      '/workspace/%s/client-extension.yaml' % projectPath,
      '/workspace/%s/Dockerfile' % projectPath,
    ] + source_deps,
    ignore=[])

  local("/workspace/gradlew :%s:createClientExtensionConfig --stacktrace" % projectPath.replace("/", ":"))

  config_json_file = "/workspace/%s/build/%s.client-extension-config.json" % (projectPath, name)

  init_metadata = False

  if yamlTemplateName != "extension_static":
    init_metadata = True

  k8s_yaml(
    local("ytt -f /repo/k8s/%s -f %s --data-value-yaml initMetadata=%s --data-value image=%s --data-value serviceId=%s --data-value virtualInstanceId=%s" 
            % (yamlTemplateName, config_json_file, init_metadata, name, name, virtual_instance_id)))

  if yamlTemplateName != "extension_job":
    objects = [
      "%s:ingress" % name,
      "%s:ingressroute" % name
    ]

  k8s_resource(
    labels=['client-extensions'],
    port_forwards=port_forwards,
    objects=['%s-%s-lxc-ext-provision-metadata:configmap' % (name, virtual_instance_id)] + objects,
    resource_deps=resource_deps,
    workload=name,
    links=links)

#for tiltfile in str(local("find /workspace -name Tiltfile -not -path '*/build/*' -not -path '*/node_modules/*' -not -path '*/node_modules_cache/*' 2>/dev/null")).splitlines():
#  include(tiltfile)

for client_extension_yaml in str(local("find /workspace/client-extensions -name client-extension.yaml -not -path '*/build/*' -not -path '*/node_modules/*' -not -path '*/node_modules_cache/*' 2>/dev/null")).splitlines():
  print(client_extension_yaml)
  print(os.path.basename(os.path.dirname(client_extension_yaml)))
  print("FILENAME: %s" % client_extension_yaml)
  print("PARENT DIR: %s" % os.path.basename(os.path.dirname(client_extension_yaml)))
  client_extension_name=os.path.basename(os.path.dirname(client_extension_yaml))
  client_extension_object=read_yaml(client_extension_yaml)
  print(type(client_extension_object))
  for item in client_extension_object.keys():
      print(item)
  if client_extension_object.get('runtime'):
    print("RUNTIME: %s" % client_extension_object['runtime']['type'])
  process_extension(client_extension_name, "client-extensions/%s" % client_extension_name, client_extension_object['runtime']['template'])